[package]
name = "apt_level_pdf_payload_creator"
version = "0.1.0"
edition = "2018"

[dependencies]
lopdf = "0.29.0"
ring = "0.16.20"
rand = "0.8.3"
base64 = "0.13.0"
sha2 = "0.9.6"
aes-gcm = "0.10.3"
